project for semantic layout
romirov/otus-css-omirov pull request #2
Opened 2023-01-17 19:57 UTC by romirov

2023-01-21 11:42 UTC, lipa88-mk requested changes
Хорошее начало! Немного перемудрили местами и добавили больше тегов-оберток чем нужно) Это хорошее стремление - стараться использовать семантические теги, но нужно и вовремя уметь остановиться) Лучшее - враг хорошего, как говориться. Есть повторяющиеся части, они не используются в вашем макете, их нужно убрать. Еще раз дублирую ссылку на макет: https://www.figma.com/file/WZBpyrcVpI1edxPzIHCg1E/Otus-mocks?t=vbSgqyfaKOjwrsdg-1 Немного доработок и будет отлично. Далее вы скорее всего  еще немного поменяете разметку, когда будете оформлять элементы - это нормально

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +        <header>MacBook Pro - 1</header>
Это излишнее, это название холста с размером экрана

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <img src="img/Line 3.png" alt="Line1">
Это одна иконка с меню, состоящая из трех линий)

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +        <article>
Не согласна с тем, что эту Артикл. Эту часть никак нельзя вынести на другой сайт без потери смысла. Это скорее секция, советовала бы заменить на нее

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <img src="img/Rectangle 1.png" alt="Rectangle 1">
Такого рода изображения излишни, это будет делаться уже стилями в дальнейшем

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            </footer>
Подвал тут тоже можно убрать, как и картинку с прямоугольником

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <img src="img/Rectangle 1.png" alt="Rectangle 1">
Тут и далее их нужно удалить из кода и из папки с картинками

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            </header>
Кажется, эта часть дублируется и излишняя

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +                    <h1>Katya
Заголовок 1 уровня уже был выше, по правилам для заголовков тут должен быть заголовок 2

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +                    “The more I deal with the work as something that is my own,  as something that is personal, the more successful it is.”
Текстовые фрагменты и цитату нужно обернуть в соответствующие теги, просто так текст мы не оставляем

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +        <article>
Теги артикл в таком формате не нужны, это просто заголовок

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <strong>Skills/</strong> Design Strategy / Marketing
Нужен тег параграфа для каждой строчки

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            </header>
Тут и далее эта часть - лишнее, ее нет в макете: https://www.figma.com/file/WZBpyrcVpI1edxPzIHCg1E/Otus-mocks?t=vbSgqyfaKOjwrsdg-1

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <a href="www.whitepapers.com"></a>
Нет текста ссылки, посмотрите на самой странице, чтобы себя проверить

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <a href="www.whitepapers.com"></a>
В адресе лучше поставить # как заглушку, чтобы случайно не переходить по этим ссылкам

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <h1>Strengths</h1>
Тут тоже нужно исправить уровень заголовка, тк 1 уже есть

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +        <article>
Артикл не нужен

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +                <h3>Strong points</h3>
Почему выбрали 3 уровень заголовка? Какие названия разделов видны на макете? Как бы вы пересказали о чем эта страница кому-либо? Это и будут заголовки 2 уровня.

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            <p>Interiors
Это не совсем параграф, это перечисление чего-то)

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +                <aside>
Асайд в данном макете не используется, его можно убрать

2023-01-21 11:42 UTC, lipa88-mk commented on index.html
> +            </footer>
Тут и везде по макету эта часть лишняя, нужно их подчистить

2023-01-23 20:22 UTC, romirov commented on index.html
> +        <header>MacBook Pro - 1</header>
Убрал

2023-01-23 20:32 UTC, romirov commented on index.html
> +            <img src="img/Line 3.png" alt="Line1">
нашел в интернете подходящую иконку и заменил три изображения на одно

2023-01-23 20:44 UTC, romirov commented on index.html
> +            <img src="img/Rectangle 1.png" alt="Rectangle 1">
Rectangle удалил

2023-01-23 20:44 UTC, romirov commented on index.html
> +            </footer>
Удалил

2023-01-23 20:45 UTC, romirov commented on index.html
> +            </header>
Удалил

2023-01-23 20:48 UTC, romirov commented on index.html
> +                    <h1>Katya
Сделано

2023-01-23 20:49 UTC, romirov commented on index.html
> +                    “The more I deal with the work as something that is my own,  as something that is personal, the more successful it is.”
Сделано

2023-01-23 21:05 UTC, romirov commented on index.html
> +        <article>
article удалил

2023-01-23 21:05 UTC, romirov commented on index.html
> +            <strong>Skills/</strong> Design Strategy / Marketing
Выставил

2023-01-23 21:05 UTC, romirov commented on index.html
> +            </header>
Удалил

2023-01-23 21:08 UTC, romirov commented on index.html
> +            <a href="www.whitepapers.com"></a>
Исправил

2023-01-23 21:11 UTC, romirov commented on index.html
> +            <h1>Strengths</h1>
Изменил на h2

2023-01-23 21:14 UTC, romirov commented on index.html
> +        <article>
Артикл убрал

2023-01-23 21:32 UTC, romirov commented on index.html
> +                <h3>Strong points</h3>
Я бы сказал, что в заключительной части перечислены сильные стороны компании, сделавшей презентацию. И акцент поставлен на слове Strengths.  Изменил на заголовок 2 уровня

2023-01-23 21:32 UTC, romirov commented on index.html
> +            <p>Interiors
Сделал перечисление

2023-01-23 21:34 UTC, romirov commented on index.html
> +                <aside>
Убрал aside

2023-01-23 21:34 UTC, romirov commented on index.html
> +            </footer>
Убрал

2023-01-26 14:38 UTC, lipa88-mk commented on index.html
> +            <img src="img/Line 3.png" alt="Line1">
Если что, то на разборе ДЗ тоже показала как это сделать

2023-01-26 14:41 UTC, lipa88-mk commented
Отлично! Далее не забудьте после мержа забрать изменения в локальный мастер/мейн

2023-01-28 09:48 UTC, merged