Typographic
romirov/otus-css-omirov pull request #3
Opened 2023-01-20 23:34 UTC by romirov

Основы работы со шрифтами и их css-свойствами

2023-01-25 16:33 UTC, lipa88-mk requested changes
В целом получилось хорошо, надо внести несколько изменений по шрифтам и правки с прошлой работы и будет супер!

2023-01-25 16:33 UTC, lipa88-mk commented on styles/style.css
> +    font-weight: 400;
Подключаете начертание 400, но оно в макете не единственное, нужно подключить все использующиеся, а их 4 штуки

2023-01-25 16:33 UTC, lipa88-mk commented on styles/style.css
> +  font-weight: 700;
Это не самый удачный вариант, тк любой новый текст будет добавлен достаточно жирным начертанием. Лучше сделать 400 и дальше уже добавлять насыщенность точечно

2023-01-25 16:33 UTC, lipa88-mk commented on styles/style.css
> +  line-height: 21px;
междустрочный интервал лучше на будущее задавать в относительных единицах, так он сохранит пропорцию при изменении базового шрифта

2023-01-25 16:33 UTC, lipa88-mk commented on styles/style.css
> +  font-size: 1rem;
Если начали использовать rem, то нужно явно указать размер текста у тега html, в пикселях. И везде далее использовать размер текста в ремах для единобразия

2023-01-25 16:33 UTC, lipa88-mk commented on styles/style.css
> +  line-height: 104px;
Правильно, что указали семейство в конце. И тут тоже высоту строки лучше пересчитать в относительные единицы (104/87), а размер текста писать в ремах

2023-01-29 18:43 UTC, romirov commented on styles/style.css
> +    font-weight: 400;
Нашел в макете еще только Butler 300. Могли бы вы уточнить, где можно найти еще 2?

2023-01-29 18:50 UTC, romirov commented on styles/style.css
> +  font-weight: 700;
Сделано

2023-01-29 19:00 UTC, romirov commented on styles/style.css
> +  line-height: 21px;
сделано

2023-01-29 19:04 UTC, romirov commented on styles/style.css
> +  font-size: 1rem;
сделано

2023-01-29 19:07 UTC, romirov commented on styles/style.css
> +  line-height: 104px;
сделано

2023-02-04 11:06 UTC, lipa88-mk commented on styles/style.css
> +    font-weight: 400;
Да, все верно, 2, это я забыла, что в обновленном макете убрали некоторые вариации.

2023-02-04 11:10 UTC, lipa88-mk requested changes
Супер, осталось поправить имя шрифта и всё будет готово. На всякий случай проверьте еще код валидатором разметки и стилей

2023-02-04 11:10 UTC, lipa88-mk commented on index.html
> +        <p class="attention_words center">Mod Studio</p>
А почему семантика поменялась?) это был заголовок 1, всё верно

2023-02-04 11:10 UTC, lipa88-mk commented on styles/style.css
> +    font-family: "Butler300";
`font-family: "Butler";` - это одно семейство, не разные. Отличаются они как раз за счет `font-weight`

2023-02-04 11:10 UTC, lipa88-mk commented on styles/style.css
> +    font-family: "Butler300";
Это нужно поправить в подключении и ниже в применениях

2023-02-06 19:04 UTC, romirov commented on index.html
> +        <p class="attention_words center">Mod Studio</p>
Вернул обратно заголовок 1.

2023-02-06 19:58 UTC, romirov commented on styles/style.css
> +    font-family: "Butler300";
сделано

2023-02-06 19:59 UTC, merged