positioning 1 section
romirov/otus-css-omirov pull request #4
Opened 2023-01-31 20:16 UTC by romirov

2023-02-02 08:53 UTC, lipa88-mk commented
Папку .idea было бы хорошо добавить в гитигнор - в гите ей не место)

2023-02-02 08:54 UTC, lipa88-mk commented
Так же в ветке нет изменений с прошлых ДЗ, вмержте пожалуйста всё в данную ветку, чтобы видеть всю картину

2023-02-02 09:00 UTC, lipa88-mk commented on styles/style.css
> +    top: 11rem;
А можно ли как-то сделать центрирование белого блока относительно секции без использования фиксированных значений?

2023-02-02 09:01 UTC, lipa88-mk commented on styles/style.css
> +.section1-text {
Позиционировать текст внутри белого блока не нужно, он просто выровнен по центру и паддингами у самого блока во все 4 второны.

2023-02-02 09:02 UTC, lipa88-mk commented on styles/style.css
> +    padding-right: 13rem;
Обычно паддинги слева и справа одинаковые

2023-02-02 09:02 UTC, lipa88-mk commented on styles/style.css
> +    margin-bottom: 2rem;
Тут нужно не само меню сдвинуть на середину страницы, а кнопку, что находится внутри меню)

2023-02-02 20:06 UTC, romirov commented on styles/style.css
> +    right: 30rem;
сделано

2023-02-02 20:10 UTC, romirov commented on styles/style.css
> +    top: 11rem;
сделано

2023-02-02 20:34 UTC, romirov commented on styles/style.css
> +.section1-text {
Сделано

2023-02-02 20:35 UTC, romirov commented on styles/style.css
> +    padding-right: 13rem;
поправил

2023-02-02 20:36 UTC, romirov commented on styles/style.css
> +    margin-bottom: 2rem;
сделано

2023-02-06 14:57 UTC, lipa88-mk requested changes

2023-02-06 14:57 UTC, lipa88-mk commented on index.html
> +    </button>
Было верно - это навигация,  в которой есть кнопка. Навигация - блочный элемент, шириной примерно 1065px, который выровнен по центру страницы. В по центру навигации расположена (пока что одна) кнопка. И тут позиционирование не нужно, это все из материала лк блочной модели

2023-02-06 14:57 UTC, lipa88-mk commented on index.html
> +    <section class="mod-studio">
Тут тоже самое - секция - блочный элемент шириной 1065 пикселей, выровненный по центру страницы. Она же - относительный контейнер для белого блока и картинки, которые позиционируются по секции абсолютно.

2023-02-06 14:57 UTC, lipa88-mk commented on styles/style.css
> +    padding-bottom: 20%;
По вертикали лучше задавать не в процентах, а фиксированные, тк на небольшом экране отступы становятся слишком малы

2023-02-06 14:57 UTC, lipa88-mk commented on styles/style.css
> +    top: 40%;
Это лишнее. Вы позиционируете белый блок, текст в нем  - это его наполнение, контент. Он сам должен выстраиваться по белому блоку. А так как `text-align: center;    line-height: 5rem;` - свойства наследуемые, то их можно передать родителю `.mod-studio-frame` и тогда див `mod-studio-text` становится вообще не нужен

2023-02-06 14:57 UTC, lipa88-mk commented on index.html
> +                    <p class="mod_studio">Mod Studio</p>
Семантически это заголовок, почему он стал параграф?)

2023-02-06 20:59 UTC, romirov commented on index.html
> +    </button>
Позиционирование убрал и добавил блок nav

2023-02-06 21:46 UTC, romirov commented on index.html
> +    <section class="mod-studio">
переделано

2023-02-06 21:48 UTC, romirov commented on styles/style.css
> +    padding-bottom: 20%;
padding убрал

2023-02-06 21:55 UTC, romirov commented on styles/style.css
> +    top: 40%;
переделано

2023-02-06 21:58 UTC, romirov commented on index.html
> +                    <p class="mod_studio">Mod Studio</p>
переделано

2023-02-11 11:27 UTC, merged