Flexbox layout
romirov/otus-css-omirov pull request #5
Opened 2023-02-08 22:10 UTC by romirov

2023-02-09 16:00 UTC, lipa88-mk requested changes
Очень хорошо, но есть еще над чем поработать и улучшить) По расположению колонок верно, остальное описала ниже. Плюс с точки зрения семантики было бы хорошо, чтобы заголовок был в разметке первым, и уже с помощью стилей он бы размещался сбоку. Например, флексами можно переставить элементы по порядку (это подсказка)

2023-02-09 16:00 UTC, lipa88-mk commented on styles/style.css
> +  margin-left: 50%;
Чтобы кнопка действительно всегда была по-середине, отступа слева, увы, не достаточно. Тк кнопка - сточно-блочный элемент, то на нее будет действовать text-align родителя - это более универсальный способ, который будет работать при уменьшении ширины экрана.

2023-02-09 16:00 UTC, lipa88-mk commented on styles/style.css
> +  margin-left: 25rem;
![image](https://user-images.githubusercontent.com/65017545/217864888-2a1a199d-403d-45a7-ae73-7a3c6218951a.png)
Задание марджинов в ремах не дает секции быть по центру страницы, тут нужен иной способ при сужении окна браузера показывать секцию по центру, не справа

2023-02-09 16:00 UTC, lipa88-mk commented on index.html
> +        <article class="katya-mills-img">
Все таки 3 разные артикл тут не очень подходят - это 3 взаимосвязанные вещи - картинка, текст и заголовок. Тут как раз ничего кроме дивов и не подойдет для создания оберток.

2023-02-09 16:00 UTC, lipa88-mk commented on index.html
> +        <article class="katya-mills-bio">
Почему заголовок 3? А где 2? Проверьте структуру страницы по заголовкам и поправьте иерархию)

2023-02-09 16:00 UTC, lipa88-mk commented on index.html
> +        <article class="katya-mills-text">
По именованию классов: секция именуется по заголовку - это биография, не важно кого. Мы можем взять ту же секцию для сайта Отсу, например, и добавить чью угодно биографию, заменив текст. И имя класса должно быть универсальным. например, biography, подошло бы лучше. Отзывы, например, testimonials. и тд. В слаке опять же была ссылка на статью с примерами классических названий имен классов, которые используются в 90% случаев.

2023-02-10 21:13 UTC, romirov commented on styles/style.css
> +  margin-left: 50%;
сделано

2023-02-11 11:07 UTC, romirov commented on styles/style.css
> +  margin-left: 25rem;
сделано

2023-02-11 11:09 UTC, romirov commented on index.html
> +        <article class="katya-mills-img">
сделано

2023-02-11 11:23 UTC, romirov commented on index.html
> +        <article class="katya-mills-bio">
переделано

2023-02-11 11:27 UTC, romirov commented on index.html
> +        <article class="katya-mills-text">
переделано

2023-02-13 18:50 UTC, merged