Grid layout
romirov/otus-css-omirov pull request #6
Opened 2023-02-15 19:42 UTC by romirov

2023-02-19 09:58 UTC, lipa88-mk requested changes
Хорошая работа! Несколько моментов со скриншотами показала ниже:

2023-02-19 09:58 UTC, lipa88-mk commented on styles/style.css
> +  display: grid;
Первое что бросается в глаза - что при уменьшении масштаба секция уезжает от центра налево
![image](https://user-images.githubusercontent.com/65017545/219940647-8883d068-d9fb-4249-85b2-087b9360dd0f.png)
Что говорит о том, что нет центрирования самой секции. Это можно сделать заданием ей максимальной ширины и автоматического марджина. И уже в этой области работать с гридовой сеткой. Так будет проще

2023-02-19 09:58 UTC, lipa88-mk commented on styles/style.css
> +.testimonials-sites{
Текст слева уезжает ниже картинки, чего не должно происходить. 
![image](https://user-images.githubusercontent.com/65017545/219940906-f2e78799-f560-4180-8032-ce0a344edbce.png)
А происходит это из-за избыточных отступов у вложенных элементов. Попробуйте поработать с сеткой так, чтобы она сама ставила элементы на места

2023-02-19 09:58 UTC, lipa88-mk commented on styles/style.css
> +  transform: rotate(-90deg);
Вместо трансформа можно еще посмотреть на https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode

2023-02-19 09:58 UTC, lipa88-mk commented on styles/style.css
> +.quote {
![image](https://user-images.githubusercontent.com/65017545/219941079-38f5a568-0206-4bd3-b76d-67d206d26a5b.png)
Элемент занимает слишком много по ширине,  как и его  родитель. Сетка тут не должна упираться в край страницы.  Уберите в тексте `br` и попробуйте сделать саму колонку такую, чтобы текст сам переносился на новую строку.

2023-02-20 21:07 UTC, romirov commented on styles/style.css
> +  display: grid;
переделано

2023-02-20 21:08 UTC, romirov commented on styles/style.css
> +.testimonials-sites{
переделано

2023-02-20 21:16 UTC, romirov commented on styles/style.css
> +  transform: rotate(-90deg);
пробовал с writing-mode: sideways-rl. Текст не развернулся.

2023-02-20 21:25 UTC, romirov commented on styles/style.css
> +.quote {
переделано

2023-02-27 19:45 UTC, merged