Designers section
romirov/otus-css-omirov pull request #7
Opened 2023-02-16 19:00 UTC by romirov

2023-02-19 10:18 UTC, lipa88-mk requested changes
Тот же момент, что и в прошлом ДЗ, показала ниже. В целом вы неплохо уже понимаете как работают сетки, но теперь нужно научиться их упрощать и пробовать предугадывать - что будет если элементов будет больше, меньше. Это убережет от переверстывания в будущем.

2023-02-19 10:18 UTC, lipa88-mk commented on styles/style.css
> +.designer-section {
section в имени класса можно не добавлять)

2023-02-19 10:18 UTC, lipa88-mk commented on styles/style.css
> +.designer-section {
И тут та же самая ситуация, что и в отзывах. Блок расползается слишком широко. Задайте ему центрирование - станет проще: 
![image](https://user-images.githubusercontent.com/65017545/219941697-77329b08-42d3-458a-8817-0f91ad72e9a6.png)

2023-02-19 10:18 UTC, lipa88-mk commented on styles/style.css
> +.designer-header {
Заголовок не обязательно должен быть частью сетки. Тем более, что в данном случае в самом задании указано, что в любой момент времени количество дизанеров может измениться и любой может быть больше по размеру. Поэтому я бы задавала сетку не на секцию, а на див после заголовка. Так тоже будет попроще.

2023-02-19 10:18 UTC, lipa88-mk commented on index.html
> +        <div class="designer-section-kameron-louisse">
С такой реализацией разметки как сделать так, чтобы второй дизайнер стал крупнее, а остальные меньше? Или как добавить 4-го или 5-го?  Думаю, что никак) Поэтому тут на всех дизайнеров нужен один контейнер, сетка которого будет располагать только карточки дизайнеров, сколько бы их не было

2023-02-21 20:09 UTC, romirov commented on styles/style.css
> +.designer-section {
сделано. Хотя не очень понятно, зачем делать секцию фиксированной ширины

2023-02-21 20:35 UTC, romirov commented on styles/style.css
> +.designer-header {
сделано

2023-02-21 21:07 UTC, romirov commented on index.html
> +        <div class="designer-section-kameron-louisse">
переделано

2023-02-27 19:45 UTC, merged